# Generated by Django 5.2.15 on 2026-07-26 00:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='purpose',
            field=models.CharField(choices=[('customer', 'Permanent / customer'), ('canonical_demo', 'Canonical demo'), ('temporary_demo', 'Temporary demo')], db_index=True, default='customer', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(condition=models.Q(('purpose__in', ('customer', 'canonical_demo', 'temporary_demo'))), name='organization_valid_purpose'),
        ),
        migrations.CreateModel(
            name='DemoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('mode', models.CharField(choices=[('prepared', 'Prepared'), ('clean', 'Clean')], max_length=10)),
                ('status', models.CharField(choices=[('provisioning', 'Provisioning'), ('active', 'Active'), ('expiring', 'Expiring'), ('deleting', 'Deleting'), ('failed', 'Failed')], default='provisioning', max_length=20)),
                ('scenario_version', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('cleanup_attempt_count', models.PositiveIntegerField(default=0)),
                ('last_cleanup_error', models.TextField(blank=True, default='')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='demo_session', to='members.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='demo_session', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('expires_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('mode__in', ('prepared', 'clean'))), name='demo_session_valid_mode'), models.CheckConstraint(condition=models.Q(('status__in', ('provisioning', 'active', 'expiring', 'deleting', 'failed'))), name='demo_session_valid_status'), models.CheckConstraint(condition=models.Q(('cleanup_attempt_count__gte', 0)), name='demo_session_cleanup_attempts_nonnegative'), models.CheckConstraint(condition=models.Q(('mode', 'clean'), models.Q(('scenario_version', ''), _negated=True), _connector='OR'), name='demo_session_prepared_has_scenario'), models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='demo_session_expiration_after_creation')],
            },
        ),
    ]
