# Generated by Django 5.2.15 on 2026-07-26 03:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_organization_purpose_demosession'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoCapacityCoordinator',
            fields=[
                ('identifier', models.CharField(default='demo-capacity', editable=False, max_length=20, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemoOperationLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('prepared', 'Prepared provisioning or reset'), ('demo_maintenance', 'Demo maintenance')], max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('acquired_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['operation', 'expires_at'], name='demo_lease_operation_exp')],
                'constraints': [models.CheckConstraint(condition=models.Q(('operation__in', ('prepared', 'demo_maintenance'))), name='demo_lease_valid_operation'), models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('acquired_at'))), name='demo_lease_future_exp')],
            },
        ),
        migrations.CreateModel(
            name='DemoPreparedResetAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('demo_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_reset_attempts', to='members.demosession')),
            ],
        ),
        migrations.CreateModel(
            name='DemoCapacityReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('mode', models.CharField(choices=[('prepared', 'Prepared'), ('clean', 'Clean')], max_length=10)),
                ('client_key', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('demo_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacity_reservations', to='members.demosession')),
            ],
            options={
                'indexes': [models.Index(fields=['mode', 'expires_at'], name='demo_reservation_mode_exp')],
                'constraints': [models.CheckConstraint(condition=models.Q(('mode__in', ('prepared', 'clean'))), name='demo_reservation_valid_mode'), models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='demo_reservation_future_exp')],
            },
        ),
        migrations.CreateModel(
            name='DemoProvisioningAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('mode', models.CharField(choices=[('prepared', 'Prepared'), ('clean', 'Clean')], max_length=10)),
                ('outcome', models.CharField(choices=[('admitted', 'Admitted'), ('capacity_denied', 'Capacity denied'), ('prepared_busy', 'Prepared operation busy'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], max_length=20)),
                ('client_key', models.CharField(max_length=64)),
                ('failure_category', models.CharField(blank=True, default='', max_length=80)),
                ('demo_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioning_attempts', to='members.demosession')),
            ],
            options={
                'indexes': [models.Index(fields=['client_key', 'created_at'], name='demo_attempt_client_time'), models.Index(fields=['mode', 'created_at'], name='demo_attempt_mode_time')],
                'constraints': [models.CheckConstraint(condition=models.Q(('mode__in', ('prepared', 'clean'))), name='demo_attempt_valid_mode'), models.CheckConstraint(condition=models.Q(('outcome__in', ('admitted', 'capacity_denied', 'prepared_busy', 'succeeded', 'failed'))), name='demo_attempt_valid_outcome')],
            },
        ),
    ]
