"""
Django settings for scheduler_project project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# This fallback is intentionally public and unsafe outside local development.
UNSAFE_DEVELOPMENT_SECRET_KEY = (
    'unsafe-development-only-secret-key-not-for-hosting'
)
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    UNSAFE_DEVELOPMENT_SECRET_KEY,
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'scheduler_app',
    'members',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'scheduler_app.middleware.TemporaryDemoSessionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'scheduler_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'members.context_processors.account_indicator',
            ],
        },
    },
]

WSGI_APPLICATION = 'scheduler_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT = BASE_DIR / 'media_root'
# this could also be 'scheduler_projet/media_root

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home-paid'
LOGOUT_REDIRECT_URL = 'login'

# Local development permits anonymous demo entry. Hosted settings override this
# with a fail-closed environment-controlled value.
DEMO_ENTRY_ENABLED = True
DEMO_MAX_ACTIVE_SESSIONS = 1000
DEMO_MAX_ACTIVE_PREPARED_SESSIONS = 500
DEMO_MAX_ACTIVE_CLEAN_SESSIONS = 500
DEMO_GLOBAL_START_LIMIT = 10000
DEMO_GLOBAL_START_WINDOW_SECONDS = 3600
DEMO_CLIENT_START_LIMIT = 10000
DEMO_CLIENT_START_WINDOW_SECONDS = 900
DEMO_MAX_CONCURRENT_PREPARED_OPERATIONS = 1
DEMO_PREPARED_RESET_LIMIT = 10000
DEMO_PREPARED_RESET_WINDOW_SECONDS = 3600
DEMO_CAPACITY_RESERVATION_SECONDS = 600
DEMO_PREPARED_OPERATION_LEASE_SECONDS = 600
DEMO_ATTEMPT_RETENTION_DAYS = 7
DEMO_MAINTENANCE_LEASE_SECONDS = 900
DEMO_MAINTENANCE_CLEANUP_LIMIT = 25
DEMO_MAINTENANCE_ATTEMPT_LIMIT = 500
DEMO_MAINTENANCE_AUXILIARY_LIMIT = 100

# Demo scaffolding is deliberately disabled unless both settings are supplied.
# The setting-based ownership check is only a temporary safety boundary for the
# read-only inspection command; it is not sufficient authorization for writes.
DEMO_SCAFFOLDING_ENABLED = (
    os.environ.get('DEMO_SCAFFOLDING_ENABLED', '').strip().lower()
    in {'1', 'true', 'yes', 'on'}
)
DEMO_ORGANIZATION_IDENTIFIER = os.environ.get(
    'DEMO_ORGANIZATION_IDENTIFIER',
    '',
).strip()
