# this file was created with the outline from the project urls file
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views
from .views import (
    CourseCreate,
    CourseDelete,
    CourseDetail,
    CourseList,
    CourseUpdate,
    LocationDelete,
    LocationDetail,
    LocationList,
    LocationCreate,
    LocationUpdate,
    SchoolCreate,
    SchoolDelete,
    SchoolDetail,
    SchoolList,
    SchoolUpdate,
    SchedCreate,
    SchedDelete,
    SchedUpdate,
    SchedList,
    SchedDetail,
    SchedGenerate,
    SchedDataRepair,
    SchedManualMoveEndpoint,
    SchedMoveConfirm,
    SchedMoveSave,
)

urlpatterns = [
    path("", views.home, name="home"),
    path("add_course", login_required(views.add_course), name="add-course"),
    path("add_school", login_required(views.add_school), name="add-school"),
    path("add_location", login_required(views.add_location), name="add-location"),
    path("home_paid", login_required(views.home_paid), name="home-paid"),
    path("add_instructor", login_required(views.add_instructor), name="add-instructor"),
    path("search_results", login_required(views.search_results), name="search-results"),
    path("class_view", login_required(views.class_view), name="class-view"),
    # class Based views below
    path("location_list", login_required(LocationList.as_view()), name="location-list"),
    path("location/<int:pk>/", login_required(LocationDetail.as_view()), name="location-detail"),
    path("add_loc", login_required(LocationCreate.as_view()), name="add-loc"),
    path("location-update/<int:pk>/", login_required(LocationUpdate.as_view()), name="location-update"),
    path("location-delete/<int:pk>/", login_required(LocationDelete.as_view()), name="location-delete"),
    # Course views
    path("course_list", login_required(CourseList.as_view()), name="course-list"),
    path("course/<int:pk>/", login_required(CourseDetail.as_view()), name="course-detail"),
    path("course_create", login_required(CourseCreate.as_view()), name="course-create"),
    path("course_update/<int:pk>/", login_required(CourseUpdate.as_view()), name="course-update"),
    path("course_delete/<int:pk>/", login_required(CourseDelete.as_view()), name="course-delete"),
    # School views
    path("school_list", login_required(SchoolList.as_view()), name="school-list"),
    path("school_detail/<int:pk>/", login_required(SchoolDetail.as_view()), name="school-detail"),
    path("school_create", login_required(SchoolCreate.as_view()), name="school-create"),
    path("school_update/<int:pk>/", login_required(SchoolUpdate.as_view()), name="school-update"),
    path("school_delete/<int:pk>/", login_required(SchoolDelete.as_view()), name="school-delete"),
    # Schedule views
    path("schedule_list", login_required(SchedList.as_view()), name="sched-list"),
    path("schedule_detail/<int:pk>/", login_required(SchedDetail.as_view()), name="sched-detail"),
    path("schedule_detail/<int:pk>/generate/", login_required(SchedGenerate.as_view()), name="sched-generate"),
    path("schedule_detail/<int:pk>/confirm-move/", login_required(SchedMoveConfirm.as_view()), name="sched-move-confirm"),
    path("schedule_detail/<int:pk>/save-move/", login_required(SchedMoveSave.as_view()), name="sched-move-save"),
    path("schedule_detail/<int:pk>/manual-move/", login_required(SchedManualMoveEndpoint.as_view()), name="sched-manual-move"),
    path("schedule_detail/<int:pk>/repair-data/", login_required(SchedDataRepair.as_view()), name="sched-data-repair"),
    path("schedule_export/<int:pk>/", login_required(views.schedule_csv_export), name="sched-export"),
    path("schedule_create", login_required(SchedCreate.as_view()), name="sched-create"),
    path("schedule_update/<int:pk>/", login_required(SchedUpdate.as_view()), name="sched-update"),
    path("schedule_delete/<int:pk>/", login_required(SchedDelete.as_view()), name="sched-delete"),
]
