# Generated by Django 3.2.9 on 2022-01-09 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.TextField(unique=True)),
                ('abriviation', models.TextField()),
                ('secondary_locs', models.TextField()),
                ('course_len', models.SmallIntegerField()),
                ('num_staff', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=450)),
                ('lname', models.CharField(max_length=450)),
                ('ropes_lead', models.BooleanField()),
                ('school_lead', models.BooleanField()),
                ('cpr', models.BooleanField(choices=[('fr', 'fresh'), ('hr', 'house'), ('boolean field', 'boolean field')])),
                ('firstaid', models.CharField(choices=[('yes', 'yes'), ('jack', 'jack')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(max_length=500, unique=True)),
                ('capicty', models.SmallIntegerField()),
                ('availible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=500, unique=True)),
                ('arrive', models.DateTimeField()),
                ('depart', models.DateTimeField()),
                ('total_students', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=120)),
                ('arrive', models.DateField()),
                ('total_students', models.SmallIntegerField()),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler_app.courses')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='primary_locs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler_app.locations'),
        ),
    ]
