# Generated by Django 3.2.9 on 2022-01-11 20:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='num_staff',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='secondary_locs',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='capicty',
        ),
        migrations.AddField(
            model_name='locations',
            name='description',
            field=models.TextField(blank=True, default='none', null=True),
        ),
        migrations.AddField(
            model_name='schools',
            name='subjects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler_app.courses'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='abriviation',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_len',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='firstaid',
            field=models.CharField(choices=[('yes', 'yes'), ('jack', 'jack'), ('charfield', 'charfield')], max_length=100),
        ),
        migrations.AlterField(
            model_name='locations',
            name='loc_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='schools',
            name='arrive',
            field=models.BooleanField(choices=[('Mon', 'Monday'), ('Tues', 'Tuesday'), ('Wed', 'Wednesday'), ('Thurs', 'Thurday'), ('Fri', 'Friday')]),
        ),
        migrations.AlterField(
            model_name='schools',
            name='depart',
            field=models.BooleanField(choices=[('Mon', 'Monday'), ('Tues', 'Tuesday'), ('Wed', 'Wednesday'), ('Thurs', 'Thurday'), ('Fri', 'Friday')]),
        ),
        migrations.AlterField(
            model_name='schools',
            name='school_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
