# Generated by Django 3.2.9 on 2022-01-11 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0002_auto_20220111_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='subjects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='scheduler_app.courses'),
        ),
    ]
