# Generated by Django 3.2.9 on 2022-01-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0003_alter_schools_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='loc_short',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
