# Generated by Django 3.2.9 on 2022-01-12 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0004_locations_loc_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='abriviation',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='primary_locs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduler_app.locations'),
        ),
    ]
