# Generated by Django 3.2.9 on 2022-01-14 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0005_auto_20220112_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prog_name', models.CharField(max_length=120, unique=True)),
                ('abriviation', models.CharField(blank=True, max_length=5, null=True, unique=True)),
                ('prog_len', models.SmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)])),
                ('primary_locz', models.ManyToManyField(to='scheduler_app.Locations')),
            ],
        ),
    ]
