# Generated by Django 3.2.9 on 2022-01-15 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0006_prog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=120, unique=True)),
                ('abriviation', models.CharField(blank=True, max_length=5, null=True, unique=True)),
                ('course_len', models.SmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)])),
                ('primary_locs', models.ManyToManyField(to='scheduler_app.Locations')),
            ],
        ),
        migrations.RemoveField(
            model_name='prog',
            name='primary_locz',
        ),
        migrations.RemoveField(
            model_name='schools',
            name='subjects',
        ),
        migrations.AlterField(
            model_name='schools',
            name='arrive',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tues', 'Tuesday'), ('Wed', 'Wednesday'), ('Thurs', 'Thurday'), ('Fri', 'Friday')], max_length=50),
        ),
        migrations.AlterField(
            model_name='schools',
            name='depart',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tues', 'Tuesday'), ('Wed', 'Wednesday'), ('Thurs', 'Thurday'), ('Fri', 'Friday')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='Prog',
        ),
        migrations.AddField(
            model_name='schools',
            name='subject',
            field=models.ManyToManyField(to='scheduler_app.Course'),
        ),
    ]
