# Generated by Django 4.0 on 2022-02-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0007_auto_20220115_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='abriviation',
            field=models.CharField(blank=True, default='5 character max', max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='availible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='description',
            field=models.TextField(blank=True, default='Notes for the new people', null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='loc_short',
            field=models.CharField(default='5 character max', max_length=5, null=True),
        ),
    ]
