# Generated by Django 4.0 on 2022-02-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0008_alter_course_abriviation_alter_locations_availible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schools',
            name='funny',
            field=models.CharField(max_length=77, null=True),
        ),
    ]
