# Generated by Django 4.0 on 2022-02-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0009_schools_funny'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schools',
            name='funny',
        ),
    ]
