# Generated by Django 3.2.9 on 2022-02-22 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0010_remove_schools_funny'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheSched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sched_name', models.CharField(max_length=150)),
                ('school_names', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler_app.schools')),
            ],
        ),
    ]
