# Generated by Django 3.2.9 on 2022-12-15 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0011_thesched'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thesched',
            old_name='school_names',
            new_name='lst_of_school_names',
        ),
        migrations.AddField(
            model_name='schools',
            name='attending_year',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
