# Generated by Django 3.2.9 on 2022-12-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0012_auto_20221215_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesched',
            name='lst_of_school_names',
        ),
        migrations.AddField(
            model_name='thesched',
            name='lst_of_school_names',
            field=models.ManyToManyField(to='scheduler_app.Schools'),
        ),
    ]
