# Generated by Django 3.2.9 on 2022-12-15 20:35

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0013_auto_20221215_1944'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='schools',
            managers=[
                ('schools_list', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='thesched',
            name='lst_of_school_names',
        ),
        migrations.AddField(
            model_name='schools',
            name='ag_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
