# Generated by Django 3.2.9 on 2022-12-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0014_auto_20221215_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='ag_num',
            field=models.IntegerField(default=1),
        ),
    ]
