# Generated by Django 3.2.9 on 2022-12-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0015_alter_schools_ag_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schools',
            name='ag_num',
        ),
        migrations.AddField(
            model_name='schools',
            name='ag_number',
            field=models.IntegerField(default=1),
        ),
    ]
