# Generated by Django 3.2.9 on 2022-12-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0016_auto_20221215_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schools',
            old_name='ag_number',
            new_name='ag_num',
        ),
    ]
