# Generated by Django 3.2.9 on 2023-01-06 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0017_rename_ag_number_schools_ag_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sort_subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorting_subjects', models.TextField()),
                ('schoolz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler_app.schools')),
            ],
        ),
    ]
