# Generated by Django 3.2.9 on 2023-01-11 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0018_sort_subjects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sort_subjects',
        ),
    ]
