# Generated by Django 4.1.5 on 2023-01-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0019_delete_sort_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='schools',
            name='sorted_subject_lst',
            field=models.TextField(default='fun'),
            preserve_default=False,
        ),
    ]
