# Generated by Django 4.1.5 on 2023-01-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0020_schools_sorted_subject_lst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='sorted_subject_lst',
            field=models.TextField(blank=True),
        ),
    ]
