# Generated by Django 3.2.9 on 2023-01-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler_app", "0021_alter_schools_sorted_subject_lst"),
    ]

    operations = [
        migrations.AddField(
            model_name="thesched",
            name="sched_data",
            field=models.JSONField(null=True),
        ),
    ]
