# Generated by Django 3.2.9 on 2026-06-01

from django.db import migrations, models
from django.utils import timezone


def backfill_schedule_creation_date(apps, schema_editor):
    TheSched = apps.get_model("scheduler_app", "TheSched")
    TheSched.objects.filter(timestamp_og__isnull=True).update(
        timestamp_og=timezone.localdate()
    )


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler_app", "0022_thesched_sched_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="thesched",
            name="timestamp_og",
            field=models.DateField(null=True),
        ),
        migrations.RunPython(
            backfill_schedule_creation_date,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="thesched",
            name="timestamp_og",
            field=models.DateField(auto_now_add=True),
        ),
    ]
