# Generated by Django 3.2.9 on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler_app", "0022_thesched_sched_data"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "scheduler_app_thesched" '
                        'ADD COLUMN "timestamp_og" date NULL'
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=(
                        'UPDATE "scheduler_app_thesched" '
                        'SET "timestamp_og" = DATE("now") '
                        'WHERE "timestamp_og" IS NULL'
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="thesched",
                    name="timestamp_og",
                    field=models.DateField(auto_now_add=True),
                ),
            ],
        ),
    ]
