# Generated by Django 3.2.9 on 2026-06-04

from django.db import migrations, models


def standardize_weekday_keys(apps, schema_editor):
    Schools = apps.get_model("scheduler_app", "Schools")
    Schools._default_manager.filter(arrive="Tues").update(arrive="Tue")
    Schools._default_manager.filter(depart="Tues").update(depart="Tue")
    Schools._default_manager.filter(arrive="Thurs").update(arrive="Thur")
    Schools._default_manager.filter(depart="Thurs").update(depart="Thur")


def restore_legacy_weekday_keys(apps, schema_editor):
    Schools = apps.get_model("scheduler_app", "Schools")
    Schools._default_manager.filter(arrive="Tue").update(arrive="Tues")
    Schools._default_manager.filter(depart="Tue").update(depart="Tues")
    Schools._default_manager.filter(arrive="Thur").update(arrive="Thurs")
    Schools._default_manager.filter(depart="Thur").update(depart="Thurs")


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler_app", "0023_thesched_timestamp_og"),
    ]

    operations = [
        migrations.RunPython(
            standardize_weekday_keys,
            reverse_code=restore_legacy_weekday_keys,
        ),
        migrations.AlterField(
            model_name="schools",
            name="arrive",
            field=models.CharField(
                choices=[
                    ("Mon", "Monday"),
                    ("Tue", "Tuesday"),
                    ("Wed", "Wednesday"),
                    ("Thur", "Thursday"),
                    ("Fri", "Friday"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="schools",
            name="depart",
            field=models.CharField(
                choices=[
                    ("Mon", "Monday"),
                    ("Tue", "Tuesday"),
                    ("Wed", "Wednesday"),
                    ("Thur", "Thursday"),
                    ("Fri", "Friday"),
                ],
                max_length=50,
            ),
        ),
    ]
