# Generated by Django 4.1.5 on 2026-06-10 22:50

from django.db import migrations, models


def attach_existing_schools_to_existing_schedules(apps, schema_editor):
    Schools = apps.get_model("scheduler_app", "Schools")
    TheSched = apps.get_model("scheduler_app", "TheSched")
    school_ids = list(Schools.schools_list.values_list("id", flat=True))
    if school_ids:
        for schedule in TheSched.objects.all():
            schedule.schools.add(*school_ids)


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler_app", "0024_standardize_school_weekday_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="thesched",
            name="schools",
            field=models.ManyToManyField(to="scheduler_app.schools"),
        ),
        migrations.RunPython(attach_existing_schools_to_existing_schedules, migrations.RunPython.noop),
    ]
