# Generated by Django 5.2.15 on 2026-06-21 21:21

import django.db.models.deletion
import scheduler_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('scheduler_app', '0025_add_schedule_schools'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(default=scheduler_app.models.get_default_organization_id, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='members.organization'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='organization',
            field=models.ForeignKey(default=scheduler_app.models.get_default_organization_id, on_delete=django.db.models.deletion.PROTECT, related_name='instructors', to='members.organization'),
        ),
        migrations.AddField(
            model_name='locations',
            name='organization',
            field=models.ForeignKey(default=scheduler_app.models.get_default_organization_id, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='members.organization'),
        ),
        migrations.AddField(
            model_name='schools',
            name='organization',
            field=models.ForeignKey(default=scheduler_app.models.get_default_organization_id, on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='members.organization'),
        ),
        migrations.AddField(
            model_name='thesched',
            name='organization',
            field=models.ForeignKey(default=scheduler_app.models.get_default_organization_id, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='members.organization'),
        ),
        migrations.AlterField(
            model_name='course',
            name='abriviation',
            field=models.CharField(blank=True, default='5 character max', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='locations',
            name='loc_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schools',
            name='school_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('organization', 'course_name'), name='unique_course_name_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(condition=models.Q(('abriviation__isnull', False)) & ~models.Q(('abriviation', '')), fields=('organization', 'abriviation'), name='unique_course_abbreviation_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='locations',
            constraint=models.UniqueConstraint(fields=('organization', 'loc_name'), name='unique_location_name_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='schools',
            constraint=models.UniqueConstraint(fields=('organization', 'school_name'), name='unique_school_name_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='thesched',
            constraint=models.UniqueConstraint(fields=('organization', 'sched_name'), name='unique_schedule_name_per_organization'),
        ),
    ]
