# Generated by Django 5.2.15 on 2026-07-12

import django.db.models.deletion
import scheduler_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('scheduler_app', '0026_course_organization_instructor_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('organization', models.ForeignKey(default=scheduler_app.models.get_default_organization_id, on_delete=django.db.models.deletion.PROTECT, related_name='certifications', to='members.organization')),
            ],
        ),
        migrations.AddConstraint(
            model_name='certification',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_certification_name_per_organization'),
        ),
    ]
