# Generated by Django 5.2.15 on 2026-07-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0027_certification'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_relationships', to='scheduler_app.certification')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_relationships', to='scheduler_app.instructor')),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='certifications',
            field=models.ManyToManyField(blank=True, related_name='instructors', through='scheduler_app.InstructorCertification', to='scheduler_app.certification'),
        ),
        migrations.AddConstraint(
            model_name='instructorcertification',
            constraint=models.UniqueConstraint(fields=('instructor', 'certification'), name='unique_instructor_certification'),
        ),
    ]
