# Generated by Django 5.2.15 on 2026-07-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0028_instructor_certification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCertificationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_requirements', to='scheduler_app.certification')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_requirements', to='scheduler_app.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='required_certifications',
            field=models.ManyToManyField(blank=True, related_name='required_by_courses', through='scheduler_app.ActivityCertificationRequirement', to='scheduler_app.certification'),
        ),
        migrations.AddConstraint(
            model_name='activitycertificationrequirement',
            constraint=models.UniqueConstraint(fields=('course', 'certification'), name='unique_activity_certification_requirement'),
        ),
    ]
