# Generated by Django 5.2.15 on 2026-07-12

import django.db.models.deletion
import scheduler_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('scheduler_app', '0029_activity_certification_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('organization', models.ForeignKey(default=scheduler_app.models.get_default_organization_id, on_delete=django.db.models.deletion.PROTECT, related_name='leadership_roles', to='members.organization')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorLeadershipRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_role_relationships', to='scheduler_app.instructor')),
                ('leadership_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_relationships', to='scheduler_app.leadershiprole')),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='leadership_roles',
            field=models.ManyToManyField(blank=True, related_name='instructors', through='scheduler_app.InstructorLeadershipRole', to='scheduler_app.leadershiprole'),
        ),
        migrations.AddConstraint(
            model_name='leadershiprole',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_leadership_role_name_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='instructorleadershiprole',
            constraint=models.UniqueConstraint(fields=('instructor', 'leadership_role'), name='unique_instructor_leadership_role'),
        ),
    ]
