# Generated by Django 5.2.15 on 2026-07-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('scheduler_app', '0030_leadership_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorScheduleAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_key', models.CharField(choices=[('mon_pm1', 'mon_pm1'), ('mon_pm2', 'mon_pm2'), ('mon_night', 'mon_night'), ('tue_am1', 'tue_am1'), ('tue_am2', 'tue_am2'), ('tue_pm1', 'tue_pm1'), ('tue_pm2', 'tue_pm2'), ('tue_night', 'tue_night'), ('wed_am1', 'wed_am1'), ('wed_am2', 'wed_am2'), ('wed_pm1', 'wed_pm1'), ('wed_pm2', 'wed_pm2'), ('wed_night', 'wed_night'), ('thur_am1', 'thur_am1'), ('thur_am2', 'thur_am2'), ('thur_pm1', 'thur_pm1'), ('thur_pm2', 'thur_pm2'), ('thur_night', 'thur_night'), ('fri_am1', 'fri_am1'), ('fri_am2', 'fri_am2')], max_length=20)),
                ('state', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], max_length=11)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_availability_records', to='scheduler_app.instructor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructor_schedule_availability_records', to='members.organization')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_availability_records', to='scheduler_app.thesched')),
            ],
        ),
        migrations.AddConstraint(
            model_name='instructorscheduleavailability',
            constraint=models.UniqueConstraint(fields=('instructor', 'schedule', 'slot_key'), name='unique_instructor_schedule_slot_availability'),
        ),
    ]
