# Generated by Django 5.2.15 on 2026-07-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0031_instructorscheduleavailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='cpr',
            field=models.BooleanField(blank=True, choices=[('fr', 'fresh'), ('hr', 'house'), ('boolean field', 'boolean field')], null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='firstaid',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('jack', 'jack'), ('charfield', 'charfield')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='ropes_lead',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='school_lead',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
