# Generated by Django 5.2.15 on 2026-07-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('scheduler_app', '0032_alter_instructor_cpr_alter_instructor_firstaid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorScheduleParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('participating', 'Participating'), ('not_participating', 'Not participating')], max_length=17)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_participation_records', to='scheduler_app.instructor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructor_schedule_participation_records', to='members.organization')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_participation_records', to='scheduler_app.thesched')),
            ],
            options={
                'ordering': ['instructor__lname', 'instructor__fname', 'instructor_id', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='instructorscheduleparticipation',
            constraint=models.UniqueConstraint(fields=('instructor', 'schedule'), name='unique_instructor_schedule_participation'),
        ),
    ]
